name: travel_planner
description: A simple travel planner
version: 0.0.6+6
environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  sign_in_button: ^3.2.0
  cloud_firestore: ^4.9.3
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

