// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHpYi3ia9Vod-QdluOoyhvEHOA84F-14',
    appId: '1:859614483839:web:5989d7351839b6dabb764a',
    messagingSenderId: '859614483839',
    projectId: 'simple-travelplanner',
    authDomain: 'simple-travelplanner.firebaseapp.com',
    storageBucket: 'simple-travelplanner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInHqmI8RDmJcgnSPfWX9uBT4aHMsoN5o',
    appId: '1:859614483839:android:95c2455c85f69bd4bb764a',
    messagingSenderId: '859614483839',
    projectId: 'simple-travelplanner',
    storageBucket: 'simple-travelplanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdvtInke9zlG5JMDmmBmIWIYg31HGN-cs',
    appId: '1:859614483839:ios:63dfd32855644249bb764a',
    messagingSenderId: '859614483839',
    projectId: 'simple-travelplanner',
    storageBucket: 'simple-travelplanner.appspot.com',
    iosClientId: '859614483839-8d7bj5892qrsrhrsuif7bmerk1t7sl84.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdvtInke9zlG5JMDmmBmIWIYg31HGN-cs',
    appId: '1:859614483839:ios:44c70551f85f2f33bb764a',
    messagingSenderId: '859614483839',
    projectId: 'simple-travelplanner',
    storageBucket: 'simple-travelplanner.appspot.com',
    iosClientId: '859614483839-bnanel6lneu0g8a92od2fevvs0180fsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPlanner.RunnerTests',
  );
}
