name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.13.6
    steps:
      - uses: actions/checkout@v2
      # - uses: dart-lang/setup-dart@v1
      # - uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.3.10'
      #     channel: stable
      #     cache: true
      #     cache-key: flutter-build-artifacts # optional, change this to force refresh cache
      #     cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter pub get
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIMPLE_TRAVELPLANNER }}'
          channelId: live
          projectId: simple-travelplanner
